### 채팅방 생성
POST {{host}}/rooms
Content-Type: application/json

{
  "name": "달구나 채팅방"
}


### 전체 채팅방 목록 조회
GET {{host}}/rooms/all
Content-Type: application/json


### 채팅방에 있는 참가자 목록 조회
GET {{host}}/rooms/e1ce4351-8b70-464a-9f60-d41b59d93bd0/participants
Content-Type: application/json


### 채팅방에 메세지 조회
GET {{host}}/rooms/e1ce4351-8b70-464a-9f60-d41b59d93bd0/participants
Content-Type: application/json